### PR TITLE
Update to list of papers

### PR DESCRIPTION
**Pull request by rsasse**
Added two CSF18 papers, SIGLOG 17 paper, missing master thesis. Additionally added authors and title to papers in the theory category.

### CODE REVIEW

**Comment by jdreier** [comment]
What about this one ?

[Distance-Bounding Protocols:
Verification without Time and Location](http://satoss.uni.lu/members/jorge/shareable/SP18_shareable.pdf)

**Comment by rsasse** [comment]
Excellent catch @jdreier ! Should be included. Category: 'using tamarin' or "tamarin extensions"?

**Comment by rsasse** [comment]
Added to extensions for now.

**Comment by jdreier** [comment]
Good question, how do we define "extension"?

**Comment by rsasse** [comment]
Well, the papers listed there so far are:
- SAPIC
- A&B
- Modeling Human Errors
- Liveness for fair exchange
Essentially, a paper that not only uses Tamarin theories in a standard way, but defines a new way and meaning to do so, without it being built into the theory itself. If that summary sounds reasonable, then the paper you linked goes here.

**Pull request merged**
