### PR TITLE
Responsive re-design of site

### PR DESCRIPTION
**Pull request by lordqwerty**
The images show the site working on a variety of devices.
Navigation is now in the form of a top bar. The top bar can toggle navigation item visibility, so on tablet it works better.

I did this to learn some bootstrap mainly. If you don't like it then feel free to reject this PR.

Desktop:
screenshot-localhost 8000-2017-10-17-23-12-16

Large android phone:
screen shot 2017-10-17 at 23 10 28

Small android phone:
screen shot 2017-10-17 at 23 09 33

iPad Air 2 (portrait): 
screen shot 2017-10-17 at 23 10 03

iPad Air 2 (landscape): 
screen shot 2017-10-17 at 23 09 54

### CODE REVIEW

**Comment by lordqwerty** [comment]
@cascremers let me know.

**Comment by rsasse** [comment]
This looks fine, so long as it still has the same functionality on desktop browsers (with a topbar instead of sidebar, that's fine). People will mostly just scroll down anyway, rather than using the links to do so.

**Comment by lordqwerty** [comment]
Yep same functionality as before. Slightly different look and works across all devices.

**Comment by rsasse** [comment]
As you were explicitly asking @cascremers about this, let's give him a chance to respond, but otherwise this looks great and I am happy to accept it. Thanks again Jorden!

**Comment by cascremers** [comment]
I'm fine with this, great work.
The only thing I'm not too sure about is the CDN thing, but if we're not
happy with that part, it is easily reverted, so why not give it a go.

Thanks,

Cas

**Pull request merged**
